### ISSUE TITLE
List of version 2 ready for review

### ISSUE THREAD

**Issue by RxLoutre** [VKGL-Kwaliteit/BioinformaticaVeldnorm#14]
- [x] Control of Documents
- [x] Requirements and Configuration management
- [x] Life cycle
- [x] Risk management
- [x] Verification and validation (Version 2 is ready!)
- [x] Introduction (https://github.com/VKGL-Kwaliteit/BioinformaticaVeldnorm/pull/21/ , Version 1 - readme)
- [x] User feedback
- [x] Software management

**Comment by rernst** [comment]
@VKGL-Kwaliteit/veldnorm Risk management v2 ready for review: #18

**Comment by hwmvandeutekom** [comment]
Ver & Val: [https://github.com/VKGL-Kwaliteit/BioinformaticaVeldnorm/pull/20](https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVKGL-Kwaliteit%2FBioinformaticaVeldnorm%2Fpull%2F20&data=05%7C02%7CH.W.M.vanDeutekom-3%40umcutrecht.nl%7C641e3b2241764e2020b708dbfb0234a5%7Cdcdf4a3dd0c04a6394cf781981249be5%7C0%7C0%7C638379759124539963%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=67Q%2F8Cx2Nk0tCBE7LBC5%2FXEw%2B1xK%2BR92NJqw4jVTwog%3D&reserved=0)
