### ISSUE TITLE
Terms to use

### ISSUE THREAD

**Issue by hwmvandeutekom** [VKGL-Kwaliteit/BioinformaticaVeldnorm#16]
Depends on the context: use either "Bioinformatics team" or "Bioinformatians"

**Comment by TLeenders** [comment]
"should" or "shall"

**Comment by hwmvandeutekom** [comment]
"biologist" vs "wetlab" vs ???

**Comment by hwmvandeutekom** [comment]
ISO norms vs ISO-15189

**Comment by Bratdaking** [comment]
"Bioinformatians" shouldn't that be "Bioinformaticians" ?

**Comment by hwmvandeutekom** [comment]
done!
