### ISSUE TITLE
Abbreviations and Definitions needed for: 

### ISSUE THREAD

**Issue by hwmvandeutekom** [VKGL-Kwaliteit/BioinformaticaVeldnorm#17]
while working on a new version, add below everything which we need to adress

**Comment by hwmvandeutekom** [comment]
QMS
IVDR
IEC
ISO

**Comment by hwmvandeutekom** [comment]
Git is a distributed version control system that tracks changes in any set of computer files.

**Comment by TLeenders** [comment]
Documents/documented
Records/recorded

**Comment by hwmvandeutekom** [comment]
added
