### ISSUE TITLE
Hotfixes

### ISSUE THREAD

**Issue by TLeenders** [VKGL-Kwaliteit/BioinformaticaVeldnorm#19]
We have discussed this briefly last meeting and came to the conclusion that this should be covered in our document. I think we should decide on how we want to approach this. Hotfixes are a nightmare for quality but oh so essential in (medical) software development.

**Comment by hwmvandeutekom** [comment]
in onze documentatie:

Hotfix: Een hotfix is een type bug, waarbij het gaat om een productie brekende issue die direct moet worden opgelost.

Een hotfix branch wordt gebruikt als een productie brekende issue direct moet worden opgelost zonder eventuele nieuwe functionaliteiten uit de develop branch over te nemen. 

Hotfix release
Aangezien het bij een hotfix gaat om een productie brekende issue, mag er afgeweken worden van de procedure van een gewone release. De betrokken bioinformatici bepalen welke versie de hotfix release krijgt en wat voor type test (integratie test of nieuwe validatie) er nodig is. In alle gevallen wordt de “Software Documentatie” aangepast op de relevante plekken.

**Comment by TLeenders** [comment]
Hotfixes zijn meegenomen onder SDLC
