### ISSUE TITLE
SOUPs

### ISSUE THREAD

**Issue by hwmvandeutekom** [VKGL-Kwaliteit/BioinformaticaVeldnorm#24]
Software of unknown provenance,

did we include it somewhere??? 

We only have a note about SOUPs in our procedure: 
SOUPs: Lijst met interne of externe tools welke gebruikt worden in de software, dus niet software welke gebruikt wordt voor het ontwikkelen zelf. 

And the list includes:
- name
- link to github
- intended purpose
- whether we use it according to the intended purpose 
- whether we need a validation (often this is part of the validation of the release itself, if you use it outside its intended purpose you need a proper validation to see that it works)
- link to publication (if there is)
- do we need version control?

**Comment by hwmvandeutekom** [comment]
IEC-62304: SOUP
software of unknown provenance (acronym)
SOFTWARE ITEM that is already developed and generally available and that has not been
developed for the purpose of being incorporated into the MEDICAL DEVICE (also known as “offthe-
shelf software”) or SOFTWARE ITEM previously developed for which adequate records of the
development PROCESSES are not available

**Comment by hwmvandeutekom** [comment]
Once solved ;) add a comment in VER&VAL with links to external databases, that they should be treated as SOUPs

**Comment by rernst** [comment]
See #32
